# Generated by Django 5.2.12 on 2026-03-18 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inscricao",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Inscrição Cadastral"
                    ),
                ),
                (
                    "distrito",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Distrito"
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Setor"
                    ),
                ),
                (
                    "quadra",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Quadra"
                    ),
                ),
                (
                    "lote",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Lote"
                    ),
                ),
                (
                    "logradouro",
                    models.TextField(blank=True, default="", verbose_name="Logradouro"),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Número"
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Bairro"
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="CEP"
                    ),
                ),
                (
                    "area_terreno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Área do Terreno (m²)",
                    ),
                ),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Área Construída (m²)",
                    ),
                ),
                (
                    "geom",
                    models.TextField(
                        blank=True, null=True, verbose_name="Geometria (WKT)"
                    ),
                ),
                (
                    "status_validacao",
                    models.CharField(
                        choices=[
                            ("ok", "Regular"),
                            ("alerta", "Alerta"),
                            ("erro", "Irregular"),
                            ("vazio", "Não vistoriado"),
                        ],
                        default="vazio",
                        max_length=20,
                        verbose_name="Status de Validação",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
                "ordering": ["inscricao"],
            },
        ),
        migrations.CreateModel(
            name="BCI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proprietario",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Proprietário",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="CPF/CNPJ"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "endereco_correspondencia",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Endereço para correspondência",
                    ),
                ),
                (
                    "tipo_dominio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pleno", "Domínio Pleno"),
                            ("util", "Domínio Útil"),
                            ("direto", "Domínio Direto"),
                            ("posse", "Posse"),
                            ("usufrutuario", "Usufrutuário"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Tipo de Domínio",
                    ),
                ),
                (
                    "area_terreno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Área do Terreno (m²)",
                    ),
                ),
                (
                    "frente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Testada Frontal (m)",
                    ),
                ),
                (
                    "fundo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Fundo (m)",
                    ),
                ),
                (
                    "lado_direito",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Lado Direito (m)",
                    ),
                ),
                (
                    "lado_esquerdo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Lado Esquerdo (m)",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("meio_quadra", "Meio de Quadra"),
                            ("esquina", "Esquina"),
                            ("encravado", "Encravado"),
                            ("vila", "Vila"),
                            ("gleba", "Gleba"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Situação na Quadra",
                    ),
                ),
                (
                    "topografia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plano", "Plano"),
                            ("aclive", "Aclive"),
                            ("declive", "Declive"),
                            ("irregular", "Irregular"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Topografia",
                    ),
                ),
                (
                    "pedologia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("seco", "Seco"),
                            ("inundavel", "Inundável"),
                            ("alagado", "Alagado"),
                            ("pantanoso", "Pantanoso"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Pedologia",
                    ),
                ),
                (
                    "nivelamento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Nivelamento",
                    ),
                ),
                (
                    "possui_construcao",
                    models.BooleanField(
                        default=False, verbose_name="Possui Construção"
                    ),
                ),
                (
                    "uso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("residencial_unifamiliar", "Residencial Unifamiliar"),
                            ("residencial_multifamiliar", "Residencial Multifamiliar"),
                            ("comercial", "Comercial"),
                            ("industrial", "Industrial"),
                            ("servicos", "Serviços"),
                            ("misto", "Misto"),
                            ("institucional", "Institucional"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Uso",
                    ),
                ),
                (
                    "tipo_construcao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("casa", "Casa"),
                            ("apartamento", "Apartamento"),
                            ("sala_comercial", "Sala Comercial"),
                            ("loja", "Loja"),
                            ("galpao", "Galpão"),
                            ("barracao", "Barracão"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Tipo de Construção",
                    ),
                ),
                (
                    "padrao_construtivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("popular", "Popular"),
                            ("simples", "Simples"),
                            ("normal", "Normal"),
                            ("bom", "Bom"),
                            ("otimo", "Ótimo"),
                            ("luxo", "Luxo"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Padrão Construtivo",
                    ),
                ),
                (
                    "estado_conservacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("otimo", "Ótimo"),
                            ("bom", "Bom"),
                            ("regular", "Regular"),
                            ("precario", "Precário"),
                            ("ruina", "Ruína"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Estado de Conservação",
                    ),
                ),
                (
                    "ano_construcao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Construção"
                    ),
                ),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Área Construída (m²)",
                    ),
                ),
                (
                    "num_pavimentos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nº Pavimentos"
                    ),
                ),
                (
                    "num_comodos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nº Cômodos"
                    ),
                ),
                (
                    "valor_venal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Venal (R$)",
                    ),
                ),
                (
                    "raw_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="JSON bruto da extração"
                    ),
                ),
                ("extraido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bcis",
                        to="cadastro.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "BCI",
                "verbose_name_plural": "BCIs",
                "ordering": ["-extraido_em"],
            },
        ),
        migrations.CreateModel(
            name="Validacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=50, verbose_name="Campo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("erro", "Erro"), ("alerta", "Alerta")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validacoes",
                        to="cadastro.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validação",
                "verbose_name_plural": "Validações",
                "ordering": ["-criado_em"],
            },
        ),
    ]
